version: '3'
volumes:
  mysql_data:

services:
  api:
    build: .
    restart: unless-stopped
    tty: true
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "8088:8088"

  mysql:
    image: mysql
    restart: unless-stopped
    volumes:
      - mysql_data:/val/lib/mysql
    ports:
      - "33060:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: uapi

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8888:8080"

  redis:
    container_name: redis
    image: redis:alpine3.19
    restart: unless-stopped
    ports:
      - "6377:6379"

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"




