import MainController from '#app/controllers/http/main-controller.js';
import AuthController from '#app/controllers/http/auth-controller.js';
import ChatListController from '#app/controllers/http/chat-list-controller.js';
import MessageController from '#app/controllers/http/message-controller.js';
import InvitationController from '#app/controllers/http/invitation-controller.js';
import NotesController from '#app/controllers/http/notes-controller.js';
import CalendarController from '#app/controllers/http/calendar-controller.js';
import TaskController from '#app/controllers/http/task-controller.js';
import ProjectController from '#app/controllers/http/project-controller.js';
import PushSubscriptionController from '#app/controllers/http/push-subscription-controller.js';

export default [
    {
        group: [
            {
                url: '/test-route-4',
                method: 'get',
                handler: MainController.testRoute,
                typeResponse: 'MainController.TestRouteResponse',
                description: 'Test route',
            },
            {
                url: '/test-tasks',
                method: 'get',
                handler: TaskController.testTasks,
                typeResponse: 'TaskController.TestTasksResponse',
                description: 'Get all tasks 4',
            },
        ],
        description: 'Test routes',
        prefix: 'test',
    },
    {
        group: [
            {
                url: '/register',
                method: 'post',
                handler: AuthController.register,
                validator: 'register',
                typeResponse: 'AuthController.RegisterResponse',
                description: 'Register a new user',
            },
            {
                url: '/login',
                method: 'post',
                handler: AuthController.login,
                validator: 'login',
                typeResponse: 'AuthController.LoginResponse',
                description: 'Login a user',
            },
            {
                url: '/logout',
                method: 'post',
                handler: AuthController.logout,
                typeResponse: 'AuthController.LogoutResponse',
                description: 'Logout a user',
                middlewares: ['auth_guard'],
            },
            {
                url: '/logout-all',
                method: 'post',
                handler: AuthController.logoutAll,
                typeResponse: 'AuthController.LogoutAllResponse',
                description: 'Logout all devices',
                middlewares: ['auth_guard'],
            },
        ],
        description: 'Auth routes',
        middlewares: ['session_web'],
        prefix: 'auth',
        rateLimit: {
            windowMs: 1 * 60 * 1000,
            maxRequests: 10,
        },
    },
    {
        group: [
            {
                url: '/get-contact-list',
                method: 'post',
                handler: ChatListController.getContactList,
                typeResponse: 'ChatListController.GetContactListResponse',
                description: 'Get contact list',
            },
            {
                url: '/chats',
                method: 'post',
                handler: ChatListController.createChat,
                validator: 'createChat',
                typeResponse: 'ChatListController.CreateChatResponse',
                description: 'Create a new chat',
            },
            {
                url: '/chats/:chatId',
                method: 'delete',
                handler: ChatListController.deleteChat,
                validator: 'deleteChat',
                typeResponse: 'ChatListController.DeleteChatResponse',
                description: 'Delete a chat',
            },
            {
                url: '/get-messages',
                method: 'post',
                handler: MessageController.getMessages,
                validator: 'getMessages',
                typeResponse: 'ChatListController.GetMessagesResponse',
                description: 'Get messages',
            },
            {
                url: '/send-chat-messages',
                method: 'post',
                handler: MessageController.sendChatMessage,
                validator: 'sendMessage',
                typeResponse: 'ChatListController.SendMessageResponse',
                description: 'Send a message',
            },
            {
                url: '/messages/:messageId',
                method: 'delete',
                handler: MessageController.deleteMessage,
                validator: 'deleteMessage',
                typeResponse: 'ChatListController.DeleteMessageResponse',
                description: 'Delete a message',
            },
            {
                url: '/messages/:messageId',
                method: 'put',
                handler: MessageController.editMessage,
                validator: 'editMessage',
                typeResponse: 'ChatListController.EditMessageResponse',
                description: 'Edit a message',
            },
            {
                url: '/messages/:messageId/read',
                method: 'put',
                handler: MessageController.markAsRead,
                validator: 'markMessageAsRead',
                typeResponse: 'ChatListController.MarkMessageAsReadResponse',
                description: 'Mark a message as read',
            },
            // Invitation Routes
            {
                url: '/invitations',
                method: 'post',
                handler: InvitationController.createInvitation,
                validator: 'createInvitation',
                typeResponse: 'InvitationController.CreateInvitationResponse',
                description: 'Create an invitation',
            },
            {
                url: '/invitations/user/:userId',
                method: 'get',
                handler: InvitationController.getUserInvitations,
                validator: 'getUserInvitations',
                typeResponse: 'InvitationController.GetUserInvitationsResponse',
                description: 'Get user invitations',
            },
        ],
        description: 'Chat routes',
        middlewares: ['session_web', 'auth_guard'],
        prefix: 'chat',
    },
    {
        group: [
            {
                url: '/init',
                method: 'get',
                handler: MainController.init,
                typeResponse: 'MainController.InitResponse',
                description: 'Initialize the main controller',
                middlewares: ['auth_guard'],
            },
            {
                url: '/update-ws-token',
                method: 'get',
                handler: MainController.updateWsToken,
                typeResponse: 'MainController.UpdateWsTokenResponse',
                description: 'Update the WebSocket token',
                middlewares: ['auth_guard'],
            },
            {
                url: '/invitations/use',
                method: 'post',
                handler: InvitationController.useInvitation,
                validator: 'useInvitation',
                typeResponse: 'InvitationController.UseInvitationResponse',
                description: 'Use an invitation',
            },
            {
                url: '/test-header/:testParam/param2/:testParam2',
                method: 'get',
                handler: MainController.testHeaders,        
                typeResponse: 'MainController.TestHeadersResponse',
                description: 'Test headers',
            },
            {
                url: '/test-cookie',
                method: 'get',
                handler: MainController.getSetCookies,
                typeResponse: 'MainController.GetSetCookiesResponse',
                description: 'Test cookies',
            },
            {
                url: '/test-session',
                method: 'get',
                handler: MainController.testSession,
                typeResponse: 'MainController.TestSessionResponse',
                description: 'Test session',
            },
            {
                url: '/save-user',
                method: 'post',
                handler: MainController.saveUser,
                validator: 'register',
                typeResponse: 'MainController.SaveUserResponse',
                description: 'Save a user',
            },
            {
                url: '/set-header-and-cookie',
                method: 'get',
                handler: MainController.setHeaderAndCookie,
                typeResponse: 'MainController.SetHeaderAndCookieResponse',
                description: 'Set header and cookie',
            },
            {
                url: '/test-middleware',
                method: 'get',
                handler: MainController.testMiddleware,
                middlewares: ['test1'],
                typeResponse: 'MainController.TestMiddlewareResponse',
                description: 'Test middleware',
            },
            {
                group: [
                    {
                        url: '/test-middleware-2',
                        method: 'get',
                        handler: MainController.testMiddleware2,
                        middlewares: ['test2'],
                    },
                    {
                        group: [
                            {
                                url: '/test-middleware-3',
                                method: 'get',
                                handler: MainController.testMiddleware3,
                                middlewares: ['test4'],
                            },
                        ],
                        middlewares: ['test3'],
                        prefix: 'test3',
                    }
                ],
                middlewares: ['test2'],
                prefix: 'test2',
            }
        ],
        description: 'Main routes',
        middlewares: ['session_web'],
        prefix: 'main',
    },
    {
        group: [
            // Notes Routes
            {
                url: '/',
                method: 'get',
                handler: NotesController.getNotes,
                typeResponse: 'NotesController.GetNotesResponse',
                description: 'Get all notes',
            },
            {
                url: '/',
                method: 'post',
                handler: NotesController.createNote,
                validator: 'createNote',
                typeResponse: 'NotesController.CreateNoteResponse',
                description: 'Create a new note',
            },
            {
                url: '/:noteId',
                method: 'get',
                handler: NotesController.getNote,
                validator: 'getNote',
                typeResponse: 'NotesController.GetNoteResponse',
                description: 'Get a note by id',
            },
            {
                url: '/:noteId',
                method: 'put',
                handler: NotesController.updateNote,
                validator: 'updateNote',
                typeResponse: 'NotesController.UpdateNoteResponse',
                description: 'Update a note by id',
            },
            {
                url: '/:noteId',
                method: 'delete',
                handler: NotesController.deleteNote,
                validator: 'deleteNote',
                typeResponse: 'NotesController.DeleteNoteResponse',
                description: 'Delete a note by id',
            },
            // Notes Photo Routes
            {
                url: '/:noteId/photos',
                method: 'post',
                handler: NotesController.addPhoto,
                validator: 'addNotePhoto',
                typeResponse: 'NotesController.AddNotePhotoResponse',
                description: 'Add a photo to a note',
            },
            {
                url: '/:noteId/photos/:photoId',
                method: 'delete',
                handler: NotesController.deletePhoto,
                validator: 'deleteNotePhoto',
                typeResponse: 'NotesController.DeleteNotePhotoResponse',
                description: 'Delete a photo from a note',
            },
        ],
        description: 'Notes routes',
        middlewares: ['session_web', 'auth_guard'],
        prefix: 'notes',
    },
    {
        group: [
            // Calendar Routes
            {
                url: '/events',
                method: 'get',
                handler: CalendarController.getEvents,
                typeResponse: 'CalendarController.GetEventsResponse',
                description: 'Get all events',
            },
            {
                url: '/events',
                method: 'post',
                handler: CalendarController.createEvent,
                validator: 'createEvent',
                typeResponse: 'CalendarController.CreateEventResponse',
                description: 'Create a new event',
            },
            {
                url: '/events/:eventId',
                method: 'get',
                handler: CalendarController.getEvent,
                validator: 'getEvent',
                typeResponse: 'CalendarController.GetEventResponse',
                description: 'Get an event by id',
            },
            {
                url: '/events/:eventId',
                method: 'put',
                handler: CalendarController.updateEvent,
                validator: 'updateEvent',
                typeResponse: 'CalendarController.UpdateEventResponse',
                description: 'Update an event by id',
            },
            {
                url: '/events/:eventId',
                method: 'delete',
                handler: CalendarController.deleteEvent,
                validator: 'deleteEvent',
                typeResponse: 'CalendarController.DeleteEventResponse',
                description: 'Delete an event by id',
            },
            // Calendar specific routes
            {
                url: '/events/date/:date',
                method: 'get',
                handler: CalendarController.getEventsByDate,
                validator: 'getEventsByDate',
                typeResponse: 'CalendarController.GetEventsByDateResponse',
                description: 'Get all events for a date',
            },
            {
                url: '/events/range',
                method: 'post',
                handler: CalendarController.getEventsByRange,
                validator: 'getEventsByRange',
                typeResponse: 'CalendarController.GetEventsByRangeResponse',
                description: 'Get all events for a range of dates',
            },
        ],
        description: 'Calendar routes',
        middlewares: ['session_web'],
        prefix: 'calendar',
    },
    {
        group: [
            // Task Routes
            {
                url: '/',
                method: 'get',
                handler: TaskController.getTasks,
                typeResponse: 'TaskController.GetTasksResponse',
                description: 'Get all tasks',
            },
            {
                url: '/',
                method: 'post',
                handler: TaskController.createTask,
                validator: 'createTask',
                typeResponse: 'TaskController.CreateTaskResponse',
                description: 'Create a new task',
            },
            {
                url: '/:taskId',
                method: 'get',
                handler: TaskController.getTask,
                validator: 'getTask',
                typeResponse: 'TaskController.GetTaskResponse',
                description: 'Get a task by id',
            },
            {
                url: '/:taskId',
                method: 'put',
                handler: TaskController.updateTask,
                validator: 'updateTask',
                typeResponse: 'TaskController.UpdateTaskResponse',
                description: 'Update a task by id',
            },
            {
                url: '/:taskId',
                method: 'delete',
                handler: TaskController.deleteTask,
                validator: 'deleteTask',
                description: 'Delete a task by id',
            },
            // Task specific routes
            {
                url: '/:taskId/status',
                method: 'put',
                handler: TaskController.updateTaskStatus,
                typeResponse: 'TaskController.UpdateTaskStatusResponse',
                validator: 'updateTaskStatus',
                description: 'Update a task status by id',  
            },
            {
                url: '/:taskId/progress',
                method: 'put',
                handler: TaskController.updateTaskProgress,
                typeResponse: 'TaskController.UpdateTaskProgressResponse',
                validator: 'updateTaskProgress',
                description: 'Update a task progress by id',
            },
            {
                url: '/project/:projectId',
                method: 'get',
                handler: TaskController.getTasksByProject,
                typeResponse: 'TaskController.GetTasksByProjectResponse',
                validator: 'getTasksByProject',
                description: 'Get all tasks for a project',
            },
            {
                url: '/:parentTaskId/subtasks',
                method: 'get',
                handler: TaskController.getSubTasks,
                typeResponse: 'TaskController.GetSubTasksResponse',
                validator: 'getSubTasks',
                description: 'Get all subtasks for a task',
            },
        ],
        description: 'Task routes',
        middlewares: ['session_web'],
        prefix: 'tasks',
    },
    {
        group: [
            // Project Routes
            {
                url: '/',
                method: 'get',
                handler: ProjectController.getProjects,
                typeResponse: 'ProjectController.GetProjectsResponse',
                description: 'Get all projects',
            },
            {
                url: '/create',
                method: 'post',
                handler: ProjectController.createProject,
                validator: 'createProject',
                typeResponse: 'ProjectController.CreateProjectResponse',
                description: 'Create a new project',
            },
            {
                url: '/:projectId',
                method: 'get',
                handler: ProjectController.getProject,
                validator: 'getProject',
                typeResponse: 'ProjectController.GetProjectResponse',
                description: 'Get a project by id',
            },
            {
                url: '/:projectId',
                method: 'put',
                handler: ProjectController.updateProject,
                validator: 'updateProject',
                typeResponse: 'ProjectController.UpdateProjectResponse',
                description: 'Update a project by id',
            },
            {
                url: '/:projectId',
                method: 'delete',
                handler: ProjectController.deleteProject,
                validator: 'deleteProject',
                typeResponse: 'ProjectController.DeleteProjectResponse',
                description: 'Delete a project by id',
            },
            // Project specific routes
            {
                url: '/:projectId/tasks',
                method: 'get',
                handler: ProjectController.getProjectTasks,
                validator: 'getProjectTasks',
                typeResponse: 'ProjectController.GetProjectTasksResponse',
                description: 'Get all tasks for a project',
            },
            {
                url: '/:projectId/statistics',
                method: 'get',
                handler: ProjectController.getProjectStatistics,
                validator: 'getProjectStatistics',
                typeResponse: 'ProjectController.GetProjectStatisticsResponse',
                description: 'Get statistics for a project',
            },
            {
                url: '/:projectId/archive',
                method: 'put',
                handler: ProjectController.archiveProject,
                validator: 'archiveProject',
                typeResponse: 'ProjectController.ArchiveProjectResponse',
                description: 'Archive a project by id',
            },
        ],
        description: 'Project routes',
        middlewares: ['session_web'],
        prefix: 'projects',
    },
    {
        group: [
            // Push Subscription Routes
            {
                url: '/',
                method: 'get',
                handler: PushSubscriptionController.getSubscriptions,
                typeResponse: 'PushSubscriptionController.GetSubscriptionsResponse',
            },
            {
                url: '/',
                method: 'post',
                handler: PushSubscriptionController.createSubscription,
                validator: 'createPushSubscription',
                typeResponse: 'PushSubscriptionController.CreateSubscriptionResponse',
            },
            {
                url: '/:subscriptionId',
                method: 'get',
                handler: PushSubscriptionController.getSubscription,
                validator: 'getPushSubscription',
                typeResponse: 'PushSubscriptionController.GetSubscriptionResponse',
            },
            {
                url: '/:subscriptionId',
                method: 'put',
                handler: PushSubscriptionController.updateSubscription,
                validator: 'updatePushSubscription',
                typeResponse: 'PushSubscriptionController.UpdateSubscriptionResponse',
            },
            {
                url: '/:subscriptionId',
                method: 'delete',
                handler: PushSubscriptionController.deleteSubscription,
                validator: 'deletePushSubscription',
                typeResponse: 'PushSubscriptionController.DeleteSubscriptionResponse',
            },
            // Push Subscription specific routes
            {
                url: '/:subscriptionId/logs',
                method: 'get',
                handler: PushSubscriptionController.getSubscriptionLogs,
                validator: 'getPushSubscriptionLogs',
                typeResponse: 'PushSubscriptionController.GetSubscriptionLogsResponse',
            },
            {
                url: '/:subscriptionId/statistics',
                method: 'get',
                handler: PushSubscriptionController.getSubscriptionStatistics,
                validator: 'getPushSubscriptionStatistics',
                typeResponse: 'PushSubscriptionController.GetSubscriptionStatisticsResponse',
            },
            {
                url: '/:subscriptionId/deactivate',
                method: 'put',
                handler: PushSubscriptionController.deactivateSubscription,
                validator: 'deactivatePushSubscription',
                typeResponse: 'PushSubscriptionController.DeactivateSubscriptionResponse',
            },
        ],
        description: 'Push Subscription routes',
        middlewares: ['session_web'],
        prefix: 'push-subscriptions',
    },
];
