import MainController from "#app/controllers/http/main-controller.js";
import AuthController from "#app/controllers/http/auth-controller.js";
import PromoController from "#app/controllers/http/promo-controller.js";
import ReferralController from "#app/controllers/http/referral-controller.js";
import PartnerController from "#app/controllers/http/partner-controller.js";
import AdminPartnerController from "#app/controllers/http/admin-partner-controller.js";
import AdminUserController from "#app/controllers/http/admin-user-controller.js";
import AdminOnlineUserController from "#app/controllers/http/admin-online-user-controller.js";
import AdminOnlineHistoryController from "#app/controllers/http/admin-online-history-controller.js";
import SupportController from "#app/controllers/http/support-controller.js";
import AdminKnowledgeBaseController from "#app/controllers/http/admin-knowledge-base-controller.js";
import ChatListController from "#app/controllers/http/chat-list-controller.js";
import MessageController from "#app/controllers/http/message-controller.js";
import InvitationController from "#app/controllers/http/invitation-controller.js";
import NotesController from "#app/controllers/http/notes-controller.js";
import CalendarController from "#app/controllers/http/calendar-controller.js";
import PushSubscriptionController from "#app/controllers/http/push-subscription-controller.js";
import AvatarController from "#app/controllers/http/avatar-controller.js";
import OAuthController from "#app/controllers/http/oauth-controller.js";
import TranslatorController from "#app/controllers/http/translator-controller.js";
import TeacherController from "#app/controllers/http/teacher-controller.js";
import TeacherSyntaxController from "#app/controllers/http/teacher-syntax-controller.js";
import TeacherSttController from "#app/controllers/http/teacher-stt-controller.js";
import TeacherSettingsController from "#app/controllers/http/teacher-settings-controller.js";
import PromptController from "#app/controllers/http/prompt-controller.js";
import LlmUsageController from "#app/controllers/http/llm-usage-controller.js";
import InworldUsageController from "#app/controllers/http/inworld-usage-controller.js";
import GrokUsageController from "#app/controllers/http/grok-usage-controller.js";
import LlmAudioUsageController from "#app/controllers/http/llm-audio-usage-controller.js";
import aiConfig from "#config/ai.js";
import { defineRoute } from "#vendor/utils/routing/define-route.js";
import * as ResponseSchemas from "shared/responses";

import {
  RegisterInputSchema,
  LoginInputSchema,
  ForgotPasswordInputSchema,
  ResetPasswordInputSchema,
  ChangePasswordInputSchema,
  VerifyEmailInputSchema,
  CreatePromoCodeInputSchema,
  RecordReferralClickInputSchema,
  CreatePartnerInputSchema,
  CreateChatInputSchema,
  DeleteChatInputSchema,
  GetMessagesInputSchema,
  SendMessageInputSchema,
  DeleteMessageInputSchema,
  EditMessageInputSchema,
  MarkMessageAsReadInputSchema,
  CreateInvitationInputSchema,
  GetUserInvitationsInputSchema,
  UseInvitationInputSchema,
  SaveUserInputSchema,
  CreateNoteInputSchema,
  UpdateNoteInputSchema,
  CreateEventInputSchema,
  UpdateEventInputSchema,
  GetEventsByRangeInputSchema,
  CreateSubscriptionInputSchema,
  UpdateSubscriptionInputSchema,
  GetContactListInputSchema,
  EditImageWithAiInputSchema,
  GenerateAvatarInputSchema,
  TeacherRecordWordPracticeInputSchema,
  TeacherSkipSyntaxPronunciationInputSchema,
  TeacherSubmitSyntaxAnswerInputSchema,
  TeacherSaveSettingsInputSchema,
  PromptUpdateInputSchema,
  PromptTestInputSchema,
  SupportKnowledgeBaseCreateSchema,
  SupportKnowledgeBaseUpdateSchema,
} from "shared/schemas";

export default [
  {
    group: [
      defineRoute({
        url: "/test-route-4",
        method: "get",
        handler: MainController.testRoute.bind(MainController),
        ResponseSchema: ResponseSchemas.TestRouteResponseSchema,
        description: "Test route",
      }),
    ],
    description: "Test routes",
    prefix: "test",
  },
  {
    group: [
      defineRoute({
        url: "/register",
        method: "post",
        handler: AuthController.register.bind(AuthController),
        validator: RegisterInputSchema,
        ResponseSchema: ResponseSchemas.RegisterResponseSchema,
        description: "Register a new user",
      }),
      defineRoute({
        url: "/login",
        method: "post",
        handler: AuthController.login.bind(AuthController),
        validator: LoginInputSchema,
        ResponseSchema: ResponseSchemas.LoginResponseSchema,
        description: "Login a user",
      }),
      defineRoute({
        url: "/logout",
        method: "post",
        handler: AuthController.logout.bind(AuthController),
        ResponseSchema: ResponseSchemas.LogoutResponseSchema,
        description: "Logout a user",
        middlewares: ["auth_guard"],
      }),
      defineRoute({
        url: "/logout-all",
        method: "post",
        handler: AuthController.logoutAll.bind(AuthController),
        ResponseSchema: ResponseSchemas.LogoutAllResponseSchema,
        description: "Logout all devices",
        middlewares: ["auth_guard"],
      }),
      defineRoute({
        url: "/change-password",
        method: "post",
        handler: AuthController.changePassword.bind(AuthController),
        validator: ChangePasswordInputSchema,
        ResponseSchema: ResponseSchemas.ChangePasswordResponseSchema,
        description: "Change or set user password",
        middlewares: ["auth_guard"],
      }),
      defineRoute({
        url: "/forgot-password",
        method: "post",
        handler: AuthController.forgotPassword.bind(AuthController),
        validator: ForgotPasswordInputSchema,
        ResponseSchema: ResponseSchemas.ForgotPasswordResponseSchema,
        description: "Request password reset email",
        rateLimit: {
          windowMs: 1 * 60 * 1000,
          maxRequests: 3,
        },
      }),
      defineRoute({
        url: "/reset-password",
        method: "post",
        handler: AuthController.resetPassword.bind(AuthController),
        validator: ResetPasswordInputSchema,
        ResponseSchema: ResponseSchemas.ResetPasswordResponseSchema,
        description: "Reset password using a one-time token",
        rateLimit: {
          windowMs: 1 * 60 * 1000,
          maxRequests: 10,
        },
      }),
      defineRoute({
        url: "/verify-email",
        method: "post",
        handler: AuthController.verifyEmail.bind(AuthController),
        validator: VerifyEmailInputSchema,
        ResponseSchema: ResponseSchemas.VerifyEmailResponseSchema,
        description: "Confirm user email by verification token",
        rateLimit: {
          windowMs: 1 * 60 * 1000,
          maxRequests: 10,
        },
      }),
      defineRoute({
        url: "/resend-verification-email",
        method: "post",
        handler: AuthController.resendVerificationEmail.bind(AuthController),
        ResponseSchema: ResponseSchemas.ResendVerificationEmailResponseSchema,
        description: "Resend verification email to authenticated user",
        middlewares: ["auth_guard"],
        rateLimit: {
          windowMs: 1 * 60 * 1000,
          maxRequests: 3,
        },
      }),
    ],
    description: "Auth routes",
    middlewares: ["session_web"],
    prefix: "auth",
    rateLimit: {
      windowMs: 1 * 60 * 1000,
      maxRequests: 10,
    },
  },
  {
    group: [
      defineRoute({
        url: "/:provider/redirect",
        method: "get",
        handler: OAuthController.redirect.bind(OAuthController),
        ResponseSchema: ResponseSchemas.OAuthRedirectResponseSchema,
        description: "Redirect to OAuth provider",
      }),
      defineRoute({
        url: "/:provider/callback",
        method: "get",
        handler: OAuthController.callback.bind(OAuthController),
        ResponseSchema: ResponseSchemas.OAuthCallbackResponseSchema,
        description: "OAuth provider callback",
      }),
    ],
    description: "OAuth routes",
    middlewares: ["session_web"],
    prefix: "auth/oauth",
    rateLimit: {
      windowMs: 1 * 60 * 1000,
      maxRequests: 20,
    },
  },
  {
    group: [
      defineRoute({
        url: "/get-contact-list",
        method: "post",
        handler: ChatListController.getContactList.bind(ChatListController),
        validator: GetContactListInputSchema,
        ResponseSchema: ResponseSchemas.GetContactListResponseSchema,
        description: "Get contact list",
      }),
      defineRoute({
        url: "/chats",
        method: "post",
        handler: ChatListController.createChat.bind(ChatListController),
        validator: CreateChatInputSchema,
        ResponseSchema: ResponseSchemas.CreateChatResponseSchema,
        description: "Create a new chat",
      }),
      defineRoute({
        url: "/chats/:chatId",
        method: "delete",
        handler: ChatListController.deleteChat.bind(ChatListController),
        validator: DeleteChatInputSchema,
        ResponseSchema: ResponseSchemas.DeleteChatResponseSchema,
        description: "Delete a chat",
      }),
      defineRoute({
        url: "/get-messages",
        method: "post",
        handler: MessageController.getMessages.bind(MessageController),
        validator: GetMessagesInputSchema,
        ResponseSchema: ResponseSchemas.GetMessagesResponseSchema,
        description: "Get messages",
      }),
      defineRoute({
        url: "/send-chat-messages",
        method: "post",
        handler: MessageController.sendChatMessage.bind(MessageController),
        validator: SendMessageInputSchema,
        ResponseSchema: ResponseSchemas.SendMessageResponseSchema,
        description: "Send a text message",
      }),
      defineRoute({
        url: "/send-chat-messages/media",
        method: "post",
        handler: MessageController.sendChatMessageMedia.bind(MessageController),
        allowedContentTypes: ["multipart"],
        ResponseSchema: ResponseSchemas.SendMessageResponseSchema,
        description: "Send a message with media file (multipart)",
      }),
      defineRoute({
        url: "/messages/:messageId",
        method: "delete",
        handler: MessageController.deleteMessage.bind(MessageController),
        validator: DeleteMessageInputSchema,
        ResponseSchema: ResponseSchemas.DeleteMessageResponseSchema,
        description: "Delete a message",
      }),
      defineRoute({
        url: "/messages/:messageId",
        method: "put",
        handler: MessageController.editMessage.bind(MessageController),
        validator: EditMessageInputSchema,
        ResponseSchema: ResponseSchemas.EditMessageResponseSchema,
        description: "Edit a message",
      }),
      defineRoute({
        url: "/messages/:messageId/read",
        method: "put",
        handler: MessageController.markAsRead.bind(MessageController),
        validator: MarkMessageAsReadInputSchema,
        ResponseSchema: ResponseSchemas.MarkMessageAsReadResponseSchema,
        description: "Mark a message as read",
      }),
      defineRoute({
        url: "/ai/edit-image",
        method: "post",
        handler: MessageController.editImageWithAi.bind(MessageController),
        allowedContentTypes: ["multipart"],
        validator: EditImageWithAiInputSchema,
        ResponseSchema: ResponseSchemas.EditChatImageWithAiResponseSchema,
        description: "Edit image with AI for chat attachments",
      }),
      // Invitation Routes
      defineRoute({
        url: "/invitations",
        method: "post",
        handler:
          InvitationController.createInvitation.bind(InvitationController),
        validator: CreateInvitationInputSchema,
        ResponseSchema: ResponseSchemas.CreateInvitationResponseSchema,
        description: "Create an invitation",
      }),
      defineRoute({
        url: "/invitations/user/:userId",
        method: "get",
        handler:
          InvitationController.getUserInvitations.bind(InvitationController),
        validator: GetUserInvitationsInputSchema,
        ResponseSchema: ResponseSchemas.GetUserInvitationsResponseSchema,
        description: "Get user invitations",
      }),
    ],
    description: "Chat routes",
    middlewares: ["session_web", "auth_guard"],
    prefix: "chat",
  },
  {
    group: [
      defineRoute({
        url: "/init",
        method: "get",
        handler: MainController.init.bind(MainController),
        ResponseSchema: ResponseSchemas.InitResponseSchema,
        description: "Initialize the main controller",
        middlewares: ["auth_guard"],
      }),
      defineRoute({
        url: "/update-ws-token",
        method: "get",
        handler: MainController.updateWsToken.bind(MainController),
        ResponseSchema: ResponseSchemas.UpdateWsTokenResponseSchema,
        description: "Update the WebSocket token",
        middlewares: ["auth_guard"],
      }),
      defineRoute({
        url: "/webrtc-ice-config",
        method: "get",
        handler: MainController.getWebrtcIceConfig.bind(MainController),
        ResponseSchema: ResponseSchemas.WebrtcIceConfigResponseSchema,
        description: "Get WebRTC ICE/TURN config",
        middlewares: ["auth_guard"],
      }),
      defineRoute({
        url: "/invitations/use",
        method: "post",
        handler: InvitationController.useInvitation.bind(InvitationController),
        validator: UseInvitationInputSchema,
        ResponseSchema: ResponseSchemas.UseInvitationResponseSchema,
        description: "Use an invitation",
      }),
      defineRoute({
        url: "/test-header/:testParam/param2/:testParam2",
        method: "get",
        handler: MainController.testHeaders.bind(MainController),
        ResponseSchema: ResponseSchemas.TestHeadersResponseSchema,
        description: "Test headers",
      }),
      defineRoute({
        url: "/test-cookie",
        method: "get",
        handler: MainController.getSetCookies.bind(MainController),
        ResponseSchema: ResponseSchemas.GetSetCookiesResponseSchema,
        description: "Test cookies",
      }),
      defineRoute({
        url: "/test-session",
        method: "get",
        handler: MainController.testSession.bind(MainController),
        ResponseSchema: ResponseSchemas.TestSessionResponseSchema,
        description: "Test session",
      }),
      defineRoute({
        url: "/save-user",
        method: "post",
        handler: MainController.saveUser.bind(MainController),
        validator: SaveUserInputSchema,
        ResponseSchema: ResponseSchemas.SaveUserResponseSchema,
        description: "Save a user",
      }),
      defineRoute({
        url: "/set-header-and-cookie",
        method: "get",
        handler: MainController.setHeaderAndCookie.bind(MainController),
        ResponseSchema: ResponseSchemas.SetHeaderAndCookieResponseSchema,
        description: "Set header and cookie",
      }),
      defineRoute({
        url: "/test-middleware",
        method: "get",
        handler: MainController.testMiddleware.bind(MainController),
        middlewares: ["test1"],
        ResponseSchema: ResponseSchemas.TestMiddlewareResponseSchema,
        description: "Test middleware",
      }),
      {
        group: [
          defineRoute({
            url: "/test-middleware-2",
            method: "get",
            handler: MainController.testMiddleware2.bind(MainController),
            middlewares: ["test2"],
            ResponseSchema: ResponseSchemas.TestMiddlewareResponseSchema,
          }),
          {
            group: [
              defineRoute({
                url: "/test-middleware-3",
                method: "get",
                handler: MainController.testMiddleware3.bind(MainController),
                middlewares: ["test4"],
                ResponseSchema: ResponseSchemas.TestMiddlewareResponseSchema,
              }),
            ],
            middlewares: ["test3"],
            prefix: "test3",
          },
        ],
        middlewares: ["test2"],
        prefix: "test2",
      },
    ],
    description: "Main routes",
    middlewares: ["session_web"],
    prefix: "main",
  },
  {
    group: [
      // Notes Routes
      defineRoute({
        url: "/",
        method: "get",
        handler: NotesController.getNotes.bind(NotesController),
        ResponseSchema: ResponseSchemas.GetNotesResponseSchema,
        description: "Get all notes",
      }),
      defineRoute({
        url: "/",
        method: "post",
        handler: NotesController.createNote.bind(NotesController),
        validator: CreateNoteInputSchema,
        ResponseSchema: ResponseSchemas.CreateNoteResponseSchema,
        description: "Create a new note",
      }),
      defineRoute({
        url: "/:noteId",
        method: "get",
        handler: NotesController.getNote.bind(NotesController),
        ResponseSchema: ResponseSchemas.GetNoteResponseSchema,
        description: "Get a note by id",
      }),
      defineRoute({
        url: "/:noteId",
        method: "put",
        handler: NotesController.updateNote.bind(NotesController),
        validator: UpdateNoteInputSchema,
        ResponseSchema: ResponseSchemas.UpdateNoteResponseSchema,
        description: "Update a note by id",
      }),
      defineRoute({
        url: "/:noteId",
        method: "delete",
        handler: NotesController.deleteNote.bind(NotesController),
        ResponseSchema: ResponseSchemas.DeleteNoteResponseSchema,
        description: "Delete a note by id",
      }),
      // Notes Photo Routes
      defineRoute({
        url: "/:noteId/photos",
        method: "post",
        handler: NotesController.addPhoto.bind(NotesController),
        allowedContentTypes: ["multipart"],
        ResponseSchema: ResponseSchemas.AddNotePhotoResponseSchema,
        description: "Add a photo to a note",
      }),
      defineRoute({
        url: "/:noteId/photos/:photoId",
        method: "delete",
        handler: NotesController.deletePhoto.bind(NotesController),
        ResponseSchema: ResponseSchemas.DeleteNotePhotoResponseSchema,
        description: "Delete a photo from a note",
      }),
    ],
    description: "Notes routes",
    middlewares: ["session_web", "auth_guard"],
    prefix: "notes",
  },
  {
    group: [
      // Calendar Routes
      defineRoute({
        url: "/events",
        method: "get",
        handler: CalendarController.getEvents.bind(CalendarController),
        ResponseSchema: ResponseSchemas.GetEventsResponseSchema,
        description: "Get all events",
      }),
      defineRoute({
        url: "/events",
        method: "post",
        handler: CalendarController.createEvent.bind(CalendarController),
        validator: CreateEventInputSchema,
        ResponseSchema: ResponseSchemas.CreateEventResponseSchema,
        description: "Create a new event",
      }),
      defineRoute({
        url: "/events/:eventId",
        method: "get",
        handler: CalendarController.getEvent.bind(CalendarController),
        ResponseSchema: ResponseSchemas.GetEventResponseSchema,
        description: "Get an event by id",
      }),
      defineRoute({
        url: "/events/:eventId",
        method: "put",
        handler: CalendarController.updateEvent.bind(CalendarController),
        validator: UpdateEventInputSchema,
        ResponseSchema: ResponseSchemas.UpdateEventResponseSchema,
        description: "Update an event by id",
      }),
      defineRoute({
        url: "/events/:eventId",
        method: "delete",
        handler: CalendarController.deleteEvent.bind(CalendarController),
        ResponseSchema: ResponseSchemas.DeleteEventResponseSchema,
        description: "Delete an event by id",
      }),
      // Calendar specific routes
      defineRoute({
        url: "/events/date/:date",
        method: "get",
        handler: CalendarController.getEventsByDate.bind(CalendarController),
        ResponseSchema: ResponseSchemas.GetEventsByDateResponseSchema,
        description: "Get all events for a date",
      }),
      defineRoute({
        url: "/events/range",
        method: "post",
        handler: CalendarController.getEventsByRange.bind(CalendarController),
        validator: GetEventsByRangeInputSchema,
        ResponseSchema: ResponseSchemas.GetEventsByRangeResponseSchema,
        description: "Get all events for a range of dates",
      }),
    ],
    description: "Calendar routes",
    middlewares: ["session_web"],
    prefix: "calendar",
  },
  {
    group: [
      // Push Subscription Routes
      defineRoute({
        url: "/vapid-public-key",
        method: "get",
        handler: PushSubscriptionController.getVapidPublicKey.bind(
          PushSubscriptionController,
        ),
        ResponseSchema: ResponseSchemas.GetVapidPublicKeyResponseSchema,
        description: "Get VAPID public key for push subscriptions",
      }),
      defineRoute({
        url: "/test-push",
        method: "get",
        handler: PushSubscriptionController.testPush.bind(
          PushSubscriptionController,
        ),
        ResponseSchema: ResponseSchemas.TestPushResponseSchema,
        description: "Send a test push notification to the current user",
      }),
      defineRoute({
        url: "/",
        method: "get",
        handler: PushSubscriptionController.getSubscriptions.bind(
          PushSubscriptionController,
        ),
        ResponseSchema: ResponseSchemas.GetSubscriptionsResponseSchema,
      }),
      defineRoute({
        url: "/",
        method: "post",
        handler: PushSubscriptionController.createSubscription.bind(
          PushSubscriptionController,
        ),
        validator: CreateSubscriptionInputSchema,
        ResponseSchema: ResponseSchemas.CreateSubscriptionResponseSchema,
      }),
      defineRoute({
        url: "/:subscriptionId",
        method: "get",
        handler: PushSubscriptionController.getSubscription.bind(
          PushSubscriptionController,
        ),
        ResponseSchema: ResponseSchemas.GetSubscriptionResponseSchema,
      }),
      defineRoute({
        url: "/:subscriptionId",
        method: "put",
        handler: PushSubscriptionController.updateSubscription.bind(
          PushSubscriptionController,
        ),
        validator: UpdateSubscriptionInputSchema,
        ResponseSchema: ResponseSchemas.UpdateSubscriptionResponseSchema,
      }),
      defineRoute({
        url: "/:subscriptionId",
        method: "delete",
        handler: PushSubscriptionController.deleteSubscription.bind(
          PushSubscriptionController,
        ),
        ResponseSchema: ResponseSchemas.DeleteSubscriptionResponseSchema,
      }),
      // Push Subscription specific routes
      defineRoute({
        url: "/:subscriptionId/logs",
        method: "get",
        handler: PushSubscriptionController.getSubscriptionLogs.bind(
          PushSubscriptionController,
        ),
        ResponseSchema: ResponseSchemas.GetSubscriptionLogsResponseSchema,
      }),
      defineRoute({
        url: "/:subscriptionId/statistics",
        method: "get",
        handler: PushSubscriptionController.getSubscriptionStatistics.bind(
          PushSubscriptionController,
        ),
        ResponseSchema: ResponseSchemas.GetSubscriptionStatisticsResponseSchema,
      }),
      defineRoute({
        url: "/:subscriptionId/deactivate",
        method: "put",
        handler: PushSubscriptionController.deactivateSubscription.bind(
          PushSubscriptionController,
        ),
        ResponseSchema: ResponseSchemas.DeactivateSubscriptionResponseSchema,
      }),
    ],
    description: "Push Subscription routes",
    middlewares: ["session_web"],
    prefix: "push-subscriptions",
  },
  {
    group: [
      defineRoute({
        url: "/upload",
        method: "post",
        handler: AvatarController.uploadAvatar.bind(AvatarController),
        allowedContentTypes: ["multipart"],
        ResponseSchema: ResponseSchemas.UploadAvatarResponseSchema,
        description: "Upload user avatar",
      }),
      defineRoute({
        url: "/generate",
        method: "post",
        handler: AvatarController.generateAvatar.bind(AvatarController),
        validator: GenerateAvatarInputSchema,
        ResponseSchema: ResponseSchemas.GenerateAvatarResponseSchema,
        description: "Generate user avatar with AI",
      }),
      defineRoute({
        url: "/",
        method: "delete",
        handler: AvatarController.deleteAvatar.bind(AvatarController),
        ResponseSchema: ResponseSchemas.DeleteAvatarResponseSchema,
        description: "Delete user avatar",
      }),
    ],
    description: "Avatar routes",
    middlewares: ["session_web", "auth_guard"],
    prefix: "avatar",
  },
  {
    group: [
      defineRoute({
        url: "/sessions",
        method: "get",
        handler: TranslatorController.getSessions.bind(TranslatorController),
        ResponseSchema: ResponseSchemas.TranslatorGetSessionsResponseSchema,
        description: "Get translator sessions",
      }),
      defineRoute({
        url: "/sessions/:sessionId/messages",
        method: "get",
        handler: TranslatorController.getSessionMessages.bind(TranslatorController),
        ResponseSchema: ResponseSchemas.TranslatorGetMessagesResponseSchema,
        description: "Get translator session messages",
      }),
      defineRoute({
        url: "/sessions/:sessionId/realtime-messages",
        method: "get",
        handler: TranslatorController.getRealtimeSessionMessages.bind(TranslatorController),
        ResponseSchema: ResponseSchemas.TranslatorGetRealtimeMessagesResponseSchema,
        description: "Get translator realtime session messages",
      }),
      defineRoute({
        url: "/sessions",
        method: "delete",
        handler: TranslatorController.deleteAllSessions.bind(TranslatorController),
        ResponseSchema: ResponseSchemas.TranslatorDeleteSessionsResponseSchema,
        description: "Delete all translator sessions for current user",
      }),
      defineRoute({
        url: "/sessions/:sessionId",
        method: "delete",
        handler: TranslatorController.deleteSession.bind(TranslatorController),
        ResponseSchema: ResponseSchemas.TranslatorDeleteSessionResponseSchema,
        description: "Delete a single translator session",
      }),
    ],
    description: "Translator routes",
    middlewares: ["session_web", "auth_guard"],
    prefix: "translator",
  },
  {
    group: [
      defineRoute({
        url: "/profile",
        method: "get",
        handler: TeacherController.getProfile.bind(TeacherController),
        ResponseSchema: ResponseSchemas.TeacherGetProfileResponseSchema,
        description: "Get teacher student profile",
      }),
      defineRoute({
        url: "/lessons",
        method: "get",
        handler: TeacherController.getLessons.bind(TeacherController),
        ResponseSchema: ResponseSchemas.TeacherGetLessonsResponseSchema,
        description: "Get teacher lessons list",
      }),
      defineRoute({
        url: "/lessons/:lessonId",
        method: "get",
        handler: TeacherController.getLessonById.bind(TeacherController),
        ResponseSchema: ResponseSchemas.TeacherGetLessonByIdResponseSchema,
        description: "Get a teacher lesson by id",
      }),
      defineRoute({
        url: "/chat/history",
        method: "get",
        handler: TeacherController.getChatHistory.bind(TeacherController),
        ResponseSchema: ResponseSchemas.TeacherGetChatHistoryResponseSchema,
        description: "Get teacher chat history",
      }),
      defineRoute({
        url: "/sessions/:sessionId/lesson",
        method: "get",
        handler: TeacherController.getSessionLessonStatus.bind(TeacherController),
        ResponseSchema: ResponseSchemas.TeacherGetSessionLessonStatusResponseSchema,
        description: "Check if a lesson exists for a translator session",
      }),
      defineRoute({
        url: "/chat/history",
        method: "delete",
        handler: TeacherController.deleteChatHistory.bind(TeacherController),
        ResponseSchema: ResponseSchemas.TeacherDeleteChatHistoryResponseSchema,
        description: "Delete all teacher chat history for current user",
      }),
      defineRoute({
        url: "/facts",
        method: "delete",
        handler: TeacherController.deleteFacts.bind(TeacherController),
        ResponseSchema: ResponseSchemas.TeacherDeleteFactsResponseSchema,
        description: "Delete all teacher facts for current user",
      }),
      defineRoute({
        url: "/lessons",
        method: "delete",
        handler: TeacherController.deleteLessons.bind(TeacherController),
        ResponseSchema: ResponseSchemas.TeacherDeleteLessonsResponseSchema,
        description: "Delete all teacher lessons for current user",
      }),
      defineRoute({
        url: "/vocabulary",
        method: "get",
        handler: TeacherController.getVocabularyCollections.bind(TeacherController),
        ResponseSchema: ResponseSchemas.TeacherGetVocabularyCollectionsResponseSchema,
        description: "Get teacher vocabulary collections",
      }),
      defineRoute({
        url: "/vocabulary/:collectionId",
        method: "get",
        handler: TeacherController.getVocabularyCollection.bind(TeacherController),
        ResponseSchema: ResponseSchemas.TeacherGetVocabularyCollectionResponseSchema,
        description: "Get teacher vocabulary collection details",
      }),
      defineRoute({
        url: "/vocabulary/:collectionId",
        method: "delete",
        handler: TeacherController.deleteVocabularyCollection.bind(TeacherController),
        ResponseSchema: ResponseSchemas.TeacherDeleteVocabularyCollectionResponseSchema,
        description: "Delete teacher vocabulary collection",
      }),
      defineRoute({
        url: "/vocabulary/:wordId/practice",
        method: "post",
        handler: TeacherController.recordWordPractice.bind(TeacherController),
        validator: TeacherRecordWordPracticeInputSchema,
        ResponseSchema: ResponseSchemas.TeacherRecordWordPracticeResponseSchema,
        description: "Record vocabulary word practice result",
      }),
      defineRoute({
        url: "/vocabulary/:wordId/audio",
        method: "get",
        handler: TeacherController.getWordAudio.bind(TeacherController),
        ResponseSchema: ResponseSchemas.TeacherWordAudioResponseSchema,
        description: "Get vocabulary word audio",
      }),
      defineRoute({
        url: "/vocabulary/example/:exampleId/audio",
        method: "get",
        handler: TeacherController.getExampleAudio.bind(TeacherController),
        ResponseSchema: ResponseSchemas.TeacherExampleAudioResponseSchema,
        description: "Get vocabulary example audio",
      }),
      // Syntax Lessons
      defineRoute({
        url: "/syntax-lessons",
        method: "get",
        handler: TeacherSyntaxController.getSyntaxLessons.bind(TeacherSyntaxController),
        ResponseSchema: ResponseSchemas.TeacherGetSyntaxLessonsResponseSchema,
        description: "Get syntax lessons list",
      }),
      defineRoute({
        url: "/syntax-lessons/:lessonId",
        method: "get",
        handler: TeacherSyntaxController.getSyntaxLesson.bind(TeacherSyntaxController),
        ResponseSchema: ResponseSchemas.TeacherGetSyntaxLessonResponseSchema,
        description: "Get syntax lesson detail",
      }),
      defineRoute({
        url: "/syntax-lessons/:lessonId",
        method: "delete",
        handler: TeacherSyntaxController.deleteSyntaxLesson.bind(TeacherSyntaxController),
        ResponseSchema: ResponseSchemas.TeacherDeleteSyntaxLessonResponseSchema,
        description: "Delete a syntax lesson",
      }),
      defineRoute({
        url: "/syntax-lessons/:lessonId/start",
        method: "post",
        handler: TeacherSyntaxController.startSyntaxAttempt.bind(TeacherSyntaxController),
        ResponseSchema: ResponseSchemas.TeacherStartSyntaxAttemptResponseSchema,
        description: "Start a practice attempt for a syntax lesson",
      }),
      defineRoute({
        url: "/syntax-lessons/:lessonId/exercises/:exerciseId/answer",
        method: "post",
        handler: TeacherSyntaxController.submitSyntaxAnswer.bind(TeacherSyntaxController),
        validator: TeacherSubmitSyntaxAnswerInputSchema,
        ResponseSchema: ResponseSchemas.TeacherSubmitSyntaxAnswerResponseSchema,
        description: "Submit answer for a syntax exercise",
      }),
      defineRoute({
        url: "/syntax-lessons/:lessonId/exercises/:exerciseId/pronunciation",
        method: "post",
        handler: TeacherSyntaxController.submitSyntaxPronunciation.bind(TeacherSyntaxController),
        allowedContentTypes: ["multipart"],
        rateLimit: {
          windowMs: aiConfig.pronunciation.localWindowMs,
          maxRequests: 1,
        },
        ResponseSchema: ResponseSchemas.TeacherSubmitSyntaxPronunciationResponseSchema,
        description: "Submit pronunciation audio for a syntax exercise",
      }),
      defineRoute({
        url: "/syntax-lessons/:lessonId/exercises/:exerciseId/pronunciation/skip",
        method: "post",
        handler: TeacherSyntaxController.skipSyntaxPronunciation.bind(TeacherSyntaxController),
        validator: TeacherSkipSyntaxPronunciationInputSchema,
        rateLimit: {
          windowMs: aiConfig.pronunciation.localWindowMs,
          maxRequests: 1,
        },
        ResponseSchema: ResponseSchemas.TeacherSkipSyntaxPronunciationResponseSchema,
        description: "Skip pronunciation step for a syntax exercise",
      }),
      defineRoute({
        url: "/syntax-lessons/:lessonId/exercises/:exerciseId/repeat-audio",
        method: "get",
        handler: TeacherSyntaxController.getSyntaxExerciseAudio.bind(TeacherSyntaxController),
        ResponseSchema: ResponseSchemas.TeacherExampleAudioResponseSchema,
        description: "Get syntax exercise repeat phrase audio",
      }),
      defineRoute({
        url: "/syntax-lessons/example/:exampleId/audio",
        method: "get",
        handler: TeacherSyntaxController.getSyntaxExampleAudio.bind(TeacherSyntaxController),
        ResponseSchema: ResponseSchemas.TeacherExampleAudioResponseSchema,
        description: "Get syntax example audio",
      }),
      defineRoute({
        url: "/stt",
        method: "post",
        handler: TeacherSttController.transcribe.bind(TeacherSttController),
        allowedContentTypes: ["multipart"],
        ResponseSchema: ResponseSchemas.TeacherSttResponseSchema,
        description: "Transcribe audio using Voxtral STT",
      }),
      defineRoute({
        url: "/voices",
        method: "get",
        handler: TeacherSettingsController.getVoices.bind(TeacherSettingsController),
        ResponseSchema: ResponseSchemas.TeacherGetVoicesResponseSchema,
        description: "Get available Inworld TTS voices",
      }),
      defineRoute({
        url: "/voices/preview",
        method: "get",
        handler: TeacherSettingsController.previewVoice.bind(TeacherSettingsController),
        ResponseSchema: ResponseSchemas.TeacherVoicePreviewResponseSchema,
        description: "Get a short audio sample for a given Inworld voice",
      }),
      defineRoute({
        url: "/settings",
        method: "get",
        handler: TeacherSettingsController.getSettings.bind(TeacherSettingsController),
        ResponseSchema: ResponseSchemas.TeacherGetSettingsResponseSchema,
        description: "Get teacher voice settings",
      }),
      defineRoute({
        url: "/settings",
        method: "put",
        handler: TeacherSettingsController.saveSettings.bind(TeacherSettingsController),
        validator: TeacherSaveSettingsInputSchema,
        ResponseSchema: ResponseSchemas.TeacherSaveSettingsResponseSchema,
        description: "Save teacher voice settings",
      }),
    ],
    description: "Teacher routes",
    middlewares: ["session_web", "auth_guard"],
    prefix: "teacher",
  },
  {
    group: [
      defineRoute({
        url: "/usage/text",
        method: "get",
        handler: LlmUsageController.getTextUsage.bind(LlmUsageController),
        ResponseSchema: ResponseSchemas.GetTextUsageResponseSchema,
        description: "Get LLM text token usage (admin)",
      }),
      defineRoute({
        url: "/usage/images",
        method: "get",
        handler: LlmUsageController.getImageUsage.bind(LlmUsageController),
        ResponseSchema: ResponseSchemas.GetImageUsageResponseSchema,
        description: "Get LLM image generation usage (admin)",
      }),
      defineRoute({
        url: "/usage/stats",
        method: "get",
        handler: LlmUsageController.getStats.bind(LlmUsageController),
        ResponseSchema: ResponseSchemas.GetUsageStatsResponseSchema,
        description: "Get LLM usage aggregate stats (admin)",
      }),
    ],
    description: "Admin LLM usage",
    middlewares: ["session_web", "auth_guard", "admin_guard"],
    prefix: "admin",
  },
  {
    group: [
      defineRoute({
        url: "/inworld/usage",
        method: "get",
        handler: InworldUsageController.getUsage.bind(InworldUsageController),
        ResponseSchema: ResponseSchemas.GetTtsUsageResponseSchema,
        description: "Get Inworld TTS usage (admin)",
      }),
      defineRoute({
        url: "/inworld/stats",
        method: "get",
        handler: InworldUsageController.getStats.bind(InworldUsageController),
        ResponseSchema: ResponseSchemas.GetTtsStatsResponseSchema,
        description: "Get Inworld TTS stats (admin)",
      }),
    ],
    description: "Admin Inworld TTS usage",
    middlewares: ["session_web", "auth_guard", "admin_guard"],
    prefix: "admin",
  },
  {
    group: [
      defineRoute({
        url: "/grok-tts/usage",
        method: "get",
        handler: GrokUsageController.getUsage.bind(GrokUsageController),
        ResponseSchema: ResponseSchemas.GetGrokTtsUsageResponseSchema,
        description: "Get Grok TTS usage (admin)",
      }),
      defineRoute({
        url: "/grok-tts/stats",
        method: "get",
        handler: GrokUsageController.getStats.bind(GrokUsageController),
        ResponseSchema: ResponseSchemas.GetGrokTtsStatsResponseSchema,
        description: "Get Grok TTS stats (admin)",
      }),
    ],
    description: "Admin Grok TTS usage",
    middlewares: ["session_web", "auth_guard", "admin_guard"],
    prefix: "admin",
  },
  {
    group: [
      defineRoute({
        url: "/audio/usage",
        method: "get",
        handler: LlmAudioUsageController.getUsage.bind(LlmAudioUsageController),
        ResponseSchema: ResponseSchemas.GetAudioUsageResponseSchema,
        description: "Get STT audio usage (admin)",
      }),
      defineRoute({
        url: "/audio/stats",
        method: "get",
        handler: LlmAudioUsageController.getStats.bind(LlmAudioUsageController),
        ResponseSchema: ResponseSchemas.GetAudioStatsResponseSchema,
        description: "Get STT audio stats (admin)",
      }),
    ],
    description: "Admin STT audio usage",
    middlewares: ["session_web", "auth_guard", "admin_guard"],
    prefix: "admin",
  },
  {
    group: [
      defineRoute({
        url: "/chat/history",
        method: "get",
        handler: SupportController.getChatHistory.bind(SupportController),
        ResponseSchema: ResponseSchemas.SupportGetChatHistoryResponseSchema,
        description: "Get support chat history",
      }),
      defineRoute({
        url: "/chat/history",
        method: "delete",
        handler: SupportController.deleteChatHistory.bind(SupportController),
        ResponseSchema: ResponseSchemas.SupportDeleteChatHistoryResponseSchema,
        description: "Delete all support chat history",
      }),
      defineRoute({
        url: "/screenshot/:articleId",
        method: "get",
        handler: SupportController.getScreenshot.bind(SupportController),
        ResponseSchema: ResponseSchemas.SupportKnowledgeBaseItemResponseSchema,
        description: "Get screenshot for a knowledge base article",
      }),
    ],
    description: "Support routes",
    middlewares: ["session_web", "auth_guard"],
    prefix: "support",
  },
  {
    group: [
      defineRoute({
        url: "/knowledge-base",
        method: "get",
        handler: AdminKnowledgeBaseController.getAll.bind(AdminKnowledgeBaseController),
        ResponseSchema: ResponseSchemas.SupportKnowledgeBaseListResponseSchema,
        description: "List all knowledge base articles",
      }),
      defineRoute({
        url: "/knowledge-base/:id",
        method: "get",
        handler: AdminKnowledgeBaseController.getById.bind(AdminKnowledgeBaseController),
        ResponseSchema: ResponseSchemas.SupportKnowledgeBaseItemResponseSchema,
        description: "Get a knowledge base article by id",
      }),
      defineRoute({
        url: "/knowledge-base",
        method: "post",
        handler: AdminKnowledgeBaseController.create.bind(AdminKnowledgeBaseController),
        validator: SupportKnowledgeBaseCreateSchema,
        ResponseSchema: ResponseSchemas.SupportKnowledgeBaseItemResponseSchema,
        description: "Create a knowledge base article",
      }),
      defineRoute({
        url: "/knowledge-base/:id",
        method: "put",
        handler: AdminKnowledgeBaseController.update.bind(AdminKnowledgeBaseController),
        validator: SupportKnowledgeBaseUpdateSchema,
        ResponseSchema: ResponseSchemas.SupportKnowledgeBaseItemResponseSchema,
        description: "Update a knowledge base article",
      }),
      defineRoute({
        url: "/knowledge-base/:id",
        method: "delete",
        handler: AdminKnowledgeBaseController.delete.bind(AdminKnowledgeBaseController),
        ResponseSchema: ResponseSchemas.SupportKnowledgeBaseDeleteResponseSchema,
        description: "Delete a knowledge base article",
      }),
      defineRoute({
        url: "/knowledge-base/:id/screenshot",
        method: "post",
        handler: AdminKnowledgeBaseController.uploadScreenshot.bind(AdminKnowledgeBaseController),
        allowedContentTypes: ["multipart"],
        ResponseSchema: ResponseSchemas.SupportKnowledgeBaseItemResponseSchema,
        description: "Upload screenshot for a knowledge base article",
      }),
      defineRoute({
        url: "/knowledge-base/:id/screenshot",
        method: "delete",
        handler: AdminKnowledgeBaseController.deleteScreenshot.bind(AdminKnowledgeBaseController),
        ResponseSchema: ResponseSchemas.SupportKnowledgeBaseItemResponseSchema,
        description: "Delete screenshot for a knowledge base article",
      }),
      defineRoute({
        url: "/knowledge-base/:id/reindex",
        method: "post",
        handler: AdminKnowledgeBaseController.reindex.bind(AdminKnowledgeBaseController),
        ResponseSchema: ResponseSchemas.SupportKnowledgeBaseReindexResponseSchema,
        description: "Reindex a knowledge base article",
      }),
      defineRoute({
        url: "/knowledge-base/reindex-all",
        method: "post",
        handler: AdminKnowledgeBaseController.reindexAll.bind(AdminKnowledgeBaseController),
        ResponseSchema: ResponseSchemas.SupportKnowledgeBaseReindexResponseSchema,
        description: "Reindex all knowledge base articles",
      }),
      defineRoute({
        url: "/knowledge-base/init",
        method: "post",
        handler: AdminKnowledgeBaseController.startInit.bind(AdminKnowledgeBaseController),
        ResponseSchema: ResponseSchemas.SupportKnowledgeBaseInitResponseSchema,
        description: "Initialize knowledge base from docs/support-knowledge-base",
      }),
      defineRoute({
        url: "/knowledge-base/init-status",
        method: "get",
        handler: AdminKnowledgeBaseController.getInitStatus.bind(AdminKnowledgeBaseController),
        ResponseSchema: ResponseSchemas.SupportKnowledgeBaseInitResponseSchema,
        description: "Get knowledge base initialization status",
      }),
    ],
    description: "Admin Knowledge Base routes",
    middlewares: ["session_web", "auth_guard", "admin_guard"],
    prefix: "admin",
  },
  {
    group: [
      defineRoute({
        url: "/",
        method: "get",
        handler: PromptController.list.bind(PromptController),
        ResponseSchema: ResponseSchemas.PromptGetListResponseSchema,
        description: "List all LLM system prompts",
      }),
      defineRoute({
        url: "/:type",
        method: "get",
        handler: PromptController.getByType.bind(PromptController),
        ResponseSchema: ResponseSchemas.PromptGetByTypeResponseSchema,
        description: "Get a LLM system prompt by type",
      }),
      defineRoute({
        url: "/:type",
        method: "put",
        handler: PromptController.update.bind(PromptController),
        validator: PromptUpdateInputSchema,
        ResponseSchema: ResponseSchemas.PromptUpdateResponseSchema,
        description: "Update a LLM system prompt by type",
      }),
      defineRoute({
        url: "/:type/test",
        method: "post",
        handler: PromptController.testPrompt.bind(PromptController),
        validator: PromptTestInputSchema,
        ResponseSchema: ResponseSchemas.PromptTestResponseSchema,
        description: "Test a LLM system prompt with a user message",
      }),
    ],
    description: "LLM Prompt management routes",
    middlewares: ["session_web", "auth_guard", "admin_guard"],
    prefix: "prompts",
  },
  // Promo code routes
  {
    group: [
      defineRoute({
        url: "/validate",
        method: "get",
        handler: PromoController.validate.bind(PromoController),
        description: "Validate a promo code (public)",
      }),
    ],
    description: "Promo routes (public)",
    middlewares: ["session_web"],
    prefix: "promo",
  },
  // Referral routes
  {
    group: [
      defineRoute({
        url: "/click",
        method: "post",
        handler: ReferralController.recordClick.bind(ReferralController),
        validator: RecordReferralClickInputSchema,
        description: "Record a referral link click (public)",
      }),
    ],
    description: "Referral routes (public)",
    middlewares: ["session_web"],
    prefix: "referral",
  },
  {
    group: [
      defineRoute({
        url: "/me",
        method: "get",
        handler: ReferralController.getMyReferralCode.bind(ReferralController),
        description: "Get my referral code and URL",
      }),
    ],
    description: "Referral routes (auth)",
    middlewares: ["session_web", "auth_guard"],
    prefix: "referral",
  },
  // Partner dashboard route
  {
    group: [
      defineRoute({
        url: "/dashboard",
        method: "get",
        handler: PartnerController.getDashboard.bind(PartnerController),
        description: "Get partner dashboard stats",
      }),
    ],
    description: "Partner routes",
    middlewares: ["session_web", "auth_guard", "partner_guard"],
    prefix: "partner",
  },
  // Admin promo code management
  {
    group: [
      defineRoute({
        url: "/promo",
        method: "get",
        handler: PromoController.list.bind(PromoController),
        description: "List all promo codes (admin)",
      }),
      defineRoute({
        url: "/promo",
        method: "post",
        handler: PromoController.create.bind(PromoController),
        validator: CreatePromoCodeInputSchema,
        description: "Create a promo code (admin)",
      }),
      defineRoute({
        url: "/promo/:id",
        method: "delete",
        handler: PromoController.deactivate.bind(PromoController),
        description: "Deactivate a promo code (admin)",
      }),
    ],
    description: "Admin promo code routes",
    middlewares: ["session_web", "auth_guard", "admin_guard"],
    prefix: "admin",
  },
  // Admin partner management
  {
    group: [
      defineRoute({
        url: "/users-online",
        method: "get",
        handler: AdminOnlineUserController.list.bind(AdminOnlineUserController),
        description: "List online users (admin)",
      }),
      defineRoute({
        url: "/history-online",
        method: "get",
        handler: AdminOnlineHistoryController.list.bind(AdminOnlineHistoryController),
        description: "List online history records (admin)",
      }),
      defineRoute({
        url: "/users-online/:id",
        method: "get",
        handler: AdminOnlineUserController.getById.bind(AdminOnlineUserController),
        description: "Get online user detail (admin)",
      }),
      defineRoute({
        url: "/users",
        method: "get",
        handler: AdminUserController.list.bind(AdminUserController),
        description: "List users with filters (admin)",
      }),
      defineRoute({
        url: "/users/search",
        method: "get",
        handler: AdminPartnerController.search.bind(AdminPartnerController),
        description: "Search user by email (admin)",
      }),
      defineRoute({
        url: "/users/:id/role",
        method: "patch",
        handler: AdminPartnerController.setRole.bind(AdminPartnerController),
        description: "Set user role (admin)",
      }),
      defineRoute({
        url: "/partners",
        method: "post",
        handler: AdminPartnerController.create.bind(AdminPartnerController),
        validator: CreatePartnerInputSchema,
        description: "Create a partner (admin)",
      }),
      defineRoute({
        url: "/partners",
        method: "get",
        handler: AdminPartnerController.list.bind(AdminPartnerController),
        description: "List all partners (admin)",
      }),
      defineRoute({
        url: "/partners/:id",
        method: "get",
        handler: AdminPartnerController.getById.bind(AdminPartnerController),
        description: "Get partner detail (admin)",
      }),
      defineRoute({
        url: "/partners/:id",
        method: "delete",
        handler: AdminPartnerController.remove.bind(AdminPartnerController),
        description: "Remove partner role (admin)",
      }),
    ],
    description: "Admin partner management routes",
    middlewares: ["session_web", "auth_guard", "admin_guard"],
    prefix: "admin",
  },
];
